version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    # environment:
    #   - BACK_URL=back:5000 # Change this if you rename the containers
    ports:
      - "80:80"
    depends_on:
      - back
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    command: --ini wsgi.ini:celery --gevent 100
    environment:
      - JWT_SECRET_KEY=PLEASE_CHANGE_ME
      - MESSAGE_BROKER="amqp://rabbitmq"
    volumes:
      - kitchenowl_data:/data
  rabbitmq:
    image: rabbitmq:3
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/

volumes:
  kitchenowl_data:
